var imagesPath  = "images/all/";

function imageNames() {
  return Object.keys(imageTextObject());
}

function imageFileNames() {
  return Object.keys(imageTextObject());
}

function imageNameFromFileName(filename) {
  var positions = [
    filename.indexOf("."),
    filename.indexOf("_"),
    // filename.indexOf('-')
  ];
  return filename
    .substr(
      0,
      Math.min.apply(
        null,
        positions.filter((x) => x > 0)
      )
    )
    .replace("&", " ");
}

function imageSelect(ops = {}) {
  return imageFileNames().filter(
    (name) => imageTextSelectFromFileName(name, ops).length > 0
  );
}

function imageAndTextSelect(ops = {}) {
  var possible = [],
    txts;
  var imgPairs = imageFileNames().forEach(function (imgName) {
    txts = imageTextSelectFromFileName(imgName, ops);
    // choose one txt from image if there are any
    if (txts.length > 0) {
      possible.push([imgName, randomSample(txts)]);
    }
  });
  return possible;
}

function imageTextSelectFromFileName(imageFileName, ops = {}) {
  const possibleWordTypes = [
    "cvc",
    "plural",
    "long",
    "sight",
    "blend",
    "digraph",
    "suffix",
    "tricky",
  ];
  var wordTypes = Object.keys(ops).filter(
    (k) => ops[k] === true && possibleWordTypes.includes(k)
  );
  const joiner = ops["combiner"];
  const imageTextObj = imageTextObject()[imageFileName];
  const keys = Object.keys(imageTextObj).filter((x) => x !== "name");
  const matchingKeys = keys.filter(function (key) {
    const matching = wordTypes.filter((x) =>
      key
        .split(" ")
        .map((y) => y.toLowerCase())
        .includes(x)
    );
    if (joiner === "All") {
      return matching.length === wordTypes.length;
    } else if (joiner === "Exactly") {
      return (
        matching.length === wordTypes.length &&
        key.split(" ").length === matching.length
      );
    } else if (joiner === "Only") {
      return matching.length === key.split(" ").length;
    } else if (joiner === "Any") {
      return matching.length > 0;
    }
  });
  const {
    maxWordLength = 20,
    maxTotalLength = 100,
    maxNumWords = 20,
    minNumWords = 1,
  } = ops;
  var possiblePhrases = flatten(
    matchingKeys
      .map((k) => imageTextObj[k])
      .filter((x) => x.length > 0 && x[0] != null)
  );
  possiblePhrases = possiblePhrases.filter((x) => x.length <= maxTotalLength);
  possiblePhrases = possiblePhrases.filter(function (x) {
    var arr = x.split(" ");
    var out = true;
    out = out && arr.length <= maxNumWords && arr.length >= minNumWords;
    out =
      out &&
      arr.length >= minNumWords &&
      Math.max(...arr.map((z) => z.length)) <= maxWordLength;
    return out;
  });
  return possiblePhrases;
}

function imageText() {
return {
	"big-bag.png":{
		"CVC":["big bag"],
		"Blend":[null],
		"CVC Digraph":['big sack'],
		"Plural":[null],
		"CVC Sight":['my big bag'],
		"Tricky":[null],
		"Long":[null]
	},
	"big-pig.png":{
		"CVC":["big pig",'fat pig','fat hog','big hog'],
		'CVC Sight':['the big pig','pig is fat']
	},
	"big-sun.png":{
		"CVC":["big sun",'hot sun'],
		'CVC Blend':['big star','hot star'],
		'CVC Sight':['our sun','sun is hot','the sun is hot','our sun is hot']
	},
	"big-web.png":{
		"CVC":["big web"],
		'CVC Sight':['his web is big']
	},
	"bit-nut.png":{
		"CVC":["bit nut"],
		'CVC Sight':['he bit the nut']
	},
	"bug-hug.png":{
		"CVC":["bug hug"],
		'CVC Sight':['hug a bug'],
		'CVC Pluar Sight':['two bugs hug']
	},
	"cat-nap.png":{
		"CVC":["cat nap"],
		'CVC Sight':['cat in bed'],
		"CVC Plural":['cats nap'],
		'CVC Plural Sight':['two cats nap'],
		'CVC Suffix Plural':['napping cats'],
		'CVC Suffix':['napping cat']
	},
	"dan-ran.png":{
		"CVC":["dan ran",'man can run'],
		"Blend":[null],
		"Digraph":[null],
		"CVC Plural":['dan runs'],
		"CVC Sight":['the man ran','he can run','he did run','run to me'],
		'CVC Suffix':['running man'],
		'CVC Suffix Sight':['the man is running'],
		"Tricky":[null],
		"Long":[null]
	},
	"dog-net.png":{
		"CVC":["dog net",'big dog net'],
		'CVC Sight':['my dog net']
	},
	"dog-wag.png":{
		"CVC":["dog wag",'dog ran far'],
		'CVC Suffix':['wagging dog','running dog']
	},
	"fat-cat.png":{
		"CVC":["fat cat"],
		'CVC Sight':['our fat cat','not a sad cat']
	},
	"fat-rat.png":{
		"CVC":["fat rat"],
		'CVC Plural':['rat legs']
	},
	"fix-map.png":{
		"CVC":["fix map"],
		'CVC Sight':['the big map']
	},
	"fun-car.png":{
		"CVC":["fun car",'fix car'],
		'CVC Sight':['my fun car','go to my car']
	},
	"hen-leg.png":{
		"CVC":["hen leg",'fat hen','big hen','red hen'],
		"Blend":[null],
		"Digraph":[null],
		"CVC Plural":['hen legs'],
		"CVC Sight":['the red hen','she is my hen'],
		"Tricky":[null],
		"Long":[null]
	},
	"hot-cup.png":{
		"CVC":["hot cup"],
		'CVC Sight':['my hot cup','i have a cup','it is my cup']
	},
	"hug-dog.png":{
		"CVC":["hug dog"],
		'CVC Suffix':['hugging dog'],
		'CVC Sight':['i hug my dog'],
		'CVC Sight Suffix':['hugging my dog']
	},
	"jan-ran.png":{
		"CVC":["jan ran"],
		'CVC Plural':['jan runs'],
		'CVC Sight Suffix':['jan is running'],
		'CVC Sight':['she ran','she ran to us']
	},
	"kid-nap.png":{
		"CVC":["kid nap"],
		'CVC Suffix':['napping kid'],
		'CVC Plural Sight':['he naps in bed']
	},
	"mad-bat.png":{
		"CVC":["mad bat"],
		'CVC Sight':['the mad bat','very mad bat','one mad bat']
	},
	"mad-cat.png":{
		"CVC":["mad cat"],
		'CVC Sight':['why is cat mad?']
	},
	"mad-pig.png":{
		"CVC":["mad pig",'mad hog'],
		'CVC Sight':['pig is very mad','how mad is pig']
	},
	"pen-tip.png":{
		"CVC":["pen tip"],
		'CVC Sight':['the pen has a tip']
	},
	"pin-tip.png":{
		"CVC":["pin tip"],
		'CVC Sight':['the pin has a tip']
	},
	"red-bed.png":{
		"CVC":["red bed"],
		'CVC Sight':['go to the bed','get in the bed']
	},
	"red-fox.png":{
		"CVC":["red fox",'red fox can run'],
		'CVC Sight':['the fox ran']
	},
	"sad-bat.png":{
		"CVC":["sad bat"],
		'CVC Sight':['he is a sad bat','the bat is sad']
	},
	"sad-cat.png":{
		"CVC":["sad cat"],
		'CVC Sight':['she is a sad cat','the cat is sad']
	},
	"sad-pig.png":{
		"CVC":["sad pig"],
		'CVC Sight':['a very sad pig']
	},
	"sad-rat.png":{
		"CVC":["sad rat"],
		'CVC Plural':['rat legs'],
		'CVC Plural Sight':['rat ears'],
		'CVC Sight':['rat ear','rat ear is big']
	},
	"sid-hid.png":{
		"CVC":["sid hid"],
		'CVC Sight':['sid in the box','sid hid in a box']
	},
	"tan-fan.png":{
		"CVC":["tan fan"],
		'CVC Sight':['fan on','fan off','fan is on','fan is off']
	},
	"tan-hat.png":{
		"CVC":["tan hat"],
		'CVC Sight':['my tan hat']
	},
	"tin-can.png":{
		"CVC":["tin can"],
		'CVC Sight':['our tin can','the tin can']
	},
	"top-lip.png":{
		"CVC":["top lip"],
		'CVC Sight Plural':['two lips','my two lips','her two lips']
	},
	"wet-cap.png":{
		"CVC":["wet cap"],
		'CVC Sight':['the cap is wet']
	},
	"wet-mop.png":{
		"CVC":["wet mop"],
		'CVC Sight':['very wet mop']
	},
	"wet-tub.png":{
		"CVC":["wet tub"],
		'CVC Sight':['my wet tub','he is in the tub']
	},
	"yuk-yam.png":{
		"CVC":["yuk yam"],
		'CVC Sight':['i do not eat yam']
	},
	"yum-ham.png":{
		"CVC":["yum ham"],
		'CVC Sight':['i eat ham','i ate the ham']
	},
	"zig-zag.jpg":{
		"CVC":["zig zag"],
		'CVC Sight':['zig and zag']
	},
	"zip-up.png":{
		"CVC":["zip up"],
		"Blend":[null],
		"Digraph":[null],
		"Plural":[null],
		"CVC Sight":['zip it up'],
		"Tricky":[null],
		"Long":[null]

	}
}; }


function imageTextObject() {
  return {
    "fish_6.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "heart_5.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pig_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shoe.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "star_7.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "acorn_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "airplane_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "alligator.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ant_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "apple_5.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "arrow.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "astronaut_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "baby_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bacon_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "badger_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bag_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bag_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ball_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "balloons_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "banana_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "barrel_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bat.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bear_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bear_6.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bear_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "beaver_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bed_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bee_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "beetle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bell_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bell_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bike_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pig_big.png": {
      CVC: ["big pig", "fat pig", "fat hog", "big hog"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["the big pig", "pig is fat"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sun_2.png": {
      CVC: ["big sun"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "web_big.png": {
      CVC: ["big web"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bike_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "binoculars_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bird_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bird_4.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "biting.png": {
      cvc: ["bit", "bud bit"],
      blend: ["bird", "bird bit", "bird bit bud"],
      long: ["bite", "bite nose", "bit nose", "bit bud on nose"],
      "plural long": ["it bites", "it bites bud"],
      "long suffix": ["biting", "biting nose", "biting bud"],
    },
    "squirrel_nut.png": {
      CVC: ["bit nut"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bobcat_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "book.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "boot.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bottle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bow_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bow_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "box_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "brain_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "brain_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bridge_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "broom_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bug_hug.png": {
      CVC: ["bug hug"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bull.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bunny.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bus_1.png": {
      CVC: ["bus", "kid bus", "kid on bus", "up on bus"],
      Plural: ["kids on bus"],
      long: ["ride bus", "bus ride", "ride on bus", "ride in bus"],
      blend: ["fast bus", "go fast bus"],
      Sight: ["go bus", "go on bus"],
    },
    "butterfly_1.png": {
      CVC: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cake_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "camel_1.png": {
      Blend: ["hump", "bump"],
      "blend plural": ["humps", "bumps"],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "car.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cardinal_3.png": {
      CVC: [null],
      Blend: ["bird"],
      "cvc blend": ["red bird"],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "carrot.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "castle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sleeping_cats.png": {
      CVC: ["cat nap"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      Suffix: ["cat napping"],
      "Plural suffix": ["cats napping"],
      "CVC Sight": [null],
      "CVC Plural": ["cats nap"],
      "CVC Tricky": [null],
    },
    "cat.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "chainsaw_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "chair_1.png": {
      CVC: ["sit on it"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "chameleon_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cheese_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cheetah_1.png": {
      CVC: ["big cat"],
      "Blend plural": ["spots"],
      "suffix blend": ["spotted"],
      "suffix blend cvc": ["spotted cat", "big spotted cat"],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "chickadee_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "chicken_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "circle.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cloud_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "coat_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "corn.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "couch_3.png": {
      CVC: ["sit on it"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cow_7.png": {
      CVC: ["cow"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "crib_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "crown.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cup_1.png": {
      name: ["cup"],
      CVC: ["cup", "hot cup"],
      "CVC Sight": ["tea cup"],
    },
    "running_5.png": {
      suffix: ["running", "running man"],
      "plural blend": ["man runs fast"],
      "suffix blend": ["running fast"],
    },
    "running_man.png": {
      CVC: ["dan ran", "man ran"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": ["dan runs", "man runs"],
      "CVC Tricky": [null],
    },
    "diamond.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "dinosaur.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "dinosaurs.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "doctor.png": {
      CVC: ["mom job", "doc jen"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "dog_8.png": {
      CVC: ["dog dug", "dog dig", "dig dog, dig", "dog dug a pit"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["my dog"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "net.png": {
      CVC: ["dog net", "big net"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["dog net is up"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "dog_run.png": {
      CVC: ["dog wag", "dog run"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "donkey.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "door.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "dragonfly_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "drum_8.png": {
      CVC: [null],
      Blend: ["drum", "big drum"],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "duck_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "eagle_1.png": {
      CVC: [null],
      Blend: ["mad bird"],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ear.png": {
      CVC: ["big ear"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "eel.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "egg.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "elephant.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "envelope.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "eye_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fairy.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cat_fat.png": {
      CVC: ["fat cat"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rat_fat.png": {
      CVC: ["fat rat"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fence.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fish_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fish_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fish.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fish_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "map.png": {
      CVC: ["fix map"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "flower_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "flute.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fly_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fork.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fridge_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "frog_1.png": {
      CVC: [null],
      Blend: ["frog", "frog on log", "frog not on a log", "I spot a frog"],
    },
    "car_5.png": {
      CVC: ["fun car"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ghost_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ghost.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "giraffe.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "glasses_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "glasses_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "goat.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "gorilla.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "grapes.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "guitar.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "hamburger.png": {
      CVC: ["bun", "yum bun", "tan bun"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "hammer.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "hand_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": ["five fingers", "fingers"],
    },
    "hat_2.png": {
      CVC: ["hat", "cap", "a cap", "hat on top", "fun hat", "hip hat"],
      blend: ["hat brim"],
    },
    "hat_4.png": {
      CVC: ["hat", "hat rim", "tan hat"],
    },
    "headphones.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "helicopter.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "hen.png": {
      CVC: ["hen leg", "red hen", "hen in pen", "hen in a pen"],
      plural: ["hen legs"],
    },
    "hexagon.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "horse_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "horse_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cup_1.png": {
      CVC: ["hot cup"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "house.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "house_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "hug_dog.png": {
      CVC: ["hug dog", "hug big dog"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["hug a dog", "hug my dog"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ice-cream.png": {
      CVC: [null],
      long: ["cone"],
    },
    "igloo.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "iguana.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "jaguar.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "jet_1.png": {
      cvc: ["jet", "jet up top"],
      blend: ["fast jet"],
      "blend sight": ["jet is fast"],
    },
    "run_woman.png": {
      CVC: ["jan ran", "run jan", "run jan, run"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": ["jan runs"],
      "CVC Tricky": [null],
    },
    "jump-rope.png": {
      CVC: [null],
      Blend: ["jump", "jump up"],
      "plural blend": ["meg jumps"],
      "blend suffix": ["jumping", "meg is jumping"],
      "long blend": ["jump rope"],
      "long plural blend": ["meg jumps rope"],
      "long blend suffix": ["jumping rope", "meg is jumping rope"],
    },
    "kangaroo_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "key_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "key_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sleep.png": {
      CVC: ["kid nap"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "king_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "kite_2.png": {
      CVC: [null],
      long: ["kite", "kite up"],
    },
    "knife_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "kudu_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ladder_1.png": {
      CVC: ["up"],
      "CVC Sight": ["go up"],
    },
    "lamp_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "laptop_1.png": {
      CVC: ["dad job"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "leaf_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "leaf_5.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "lion_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "llama_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bat_mad.png": {
      CVC: ["mad bat"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cat_mad.png": {
      CVC: ["mad cat"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "boar_1.png": {
      CVC: ["mad pig"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "mailbox_1.png": {
      CVC: ["box"],
      Blend: ["flag", "flag up"],
      "CVC Digraph": [null],
      Plural: [null],
      "blend Sight": ["flag is up"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "marlin_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "maze_1.png": {
      CVC: [null],
      long: ["maze"],
    },
    "mole_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "moose_1.jpg": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "moth_1.png": {
      CVC: [null],
      Blend: [null],
      Digraph: ["moth", "a moth"],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "mouse_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "muffin_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "mug_8.png": {
      CVC: ["mug"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["it is a mug"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "nose_1.png": {
      CVC: [null],
      long: ["nose"],
    },
    "octopus_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ostrich_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "outlet_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "owl_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      Sight: ["owl", "owl is up", "owl sits"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "paintbrush_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pan_4.png": {
      CVC: ["tin pan", "hot pan", "in a pan", "on a pan"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pancakes_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "panda_6.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pants_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "parallelogram.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pear_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pen_tip.png": {
      CVC: ["pen tip"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["pen is up"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "penguin_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pentagon.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "phone_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "phone_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "keyboard_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "piano_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pig_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pig.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pikachu_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pin_tip.png": {
      CVC: ["pin tip"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pineapple_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pizza_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "plane.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "plane_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "polka-dots_1.jpg": {
      cvc: ["dot", "dot on top"],
      plural: ["dots", "dots on top"],
    },
    "popsicle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pot_3.png": {
      cvc: ["pot", "hot pot", "lid on pot", "pot lid"],
    },
    "psyduck_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pumpkin.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "purse_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pyramid_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "quail_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "queen.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rabbit_head.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "racoon_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rag_1.png": {
      CVC: ["rag", "a rag", "wet rag"],
      long: ["wipe", "wipe rag"],
      suffix: ["wiping"],
    },
    "rake_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rat_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rat_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rat.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rectangle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rectangle.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fox_1.png": {
      CVC: ["red fox", "fox not in box", "not a fat fox"],
      digraph: ["thin fox", "a thin fox"],
      "digraph sight": ["fox is thin"],
    },
    "ribs_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rice_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "robot_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rocket_4.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rocket_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rooster_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rose_5.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "bat_sad.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cat_sad.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "pig_sad.png": {
      CVC: ["sad pig", "pig in a pen", "pig in pen"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "rat_sad.png": {
      CVC: ["sad rat"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sailboat.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sandals_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "santa_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "saturn_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "saw.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "scissors.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "scissors.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "scooter_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "screwdriver_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "seahorse_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "seal_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "semicircle.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shark_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shark_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sheep_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shell_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shirt_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shoes_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shot_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "shovel_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "hiding.png": {
      CVC: ["sid hid", "sid hid in a box", "sid in box", "hid in box"],
      long: ["hide", "hide in box"],
    },
    "sitting_1.png": {
      cvc: ["sit"],
      plural: ["jen sits"],
      suffix: ["sitting", "jen is sitting"],
    },
    "slide_4.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "sloth_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "snail_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "snake_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "snowman_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "snowman_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "snowman_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "soccer-ball.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "socks_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "soup_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "spider_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "spider_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "spoon_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "square.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "squid_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "squirrel_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "stairs.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "star.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "stethoscope.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "stool_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "strawberry_1.png": {
      CVC: [null],
    },
    "submarine.png": {
      CVC: ["sub", "wet sub"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["sub in tub"],
    },
    "sun_1.png": {
      CVC: [null],
    },
    "sweater_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "swing_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "tag_1.png": {
      cvc: ["tag", "a tag", "a red tag"],
      long: ["price tag"],
    },
    "table_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "fan_1.png": {
      CVC: ["tan fan"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "telescope_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "tent_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "can_1.png": {
      CVC: ["tin can"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "toilet_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "tooth_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "lips.png": {
      CVC: ["top lip"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: ["lips"],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "train_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "trapezoid.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "tree.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "tree_8.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "trees_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "triangle.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "triangle_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "truck_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "trumpet_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "turkey_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "turtle_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "turtle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "umbrella_2.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "umbrella_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "unicycle_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "violin_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "wagon_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "wagon_3.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "walrus_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "watch_5.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "web.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "cap.png": {
      CVC: ["cap", "hat", "wet hat", "wet cap", "red cap"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "mop_1.png": {
      CVC: ["wet mop", "mop up"],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": ["dad mops", "dad mops up"],
      "CVC Tricky": [null],
    },
    "tub_1.png": {
      CVC: ["wet tub"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["in the tub"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "whale_4.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "witch.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "wolf_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "wrench_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "yam_1.png": {
      CVC: ["yuk yam"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "ham.png": {
      CVC: ["yum ham", "big ham", "a big ham", "get a ham"],
      long: ["ham bone"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "zebra_1.png": {
      CVC: [null],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": [null],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "zig-zag.jpg": {
      CVC: ["zig zag"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["zig and zag"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
    "zipper_1.png": {
      name: ["zipper"],
      CVC: ["zip up"],
      Blend: [null],
      "CVC Digraph": [null],
      Plural: [null],
      "CVC Sight": ["zip it up", "I zip up", "zip me up"],
      "CVC Plural": [null],
      "CVC Tricky": [null],
    },
  };
}

function imageSynonyms() {
  return {
    zipper_1: [],
    "zebra_1.png": [],
  };
}
